default: &default
  story_types:
    - 民事
    - 刑事
    - 少年
    - 行政
  crawler_kinds:
    crawler_court: "法院錯誤"
    crawler_judge: "法官錯誤"
    crawler_branch: "股別錯誤"
    crawler_schedule: "庭期錯誤"
    crawler_verdict: "判決書錯誤"
  crawler_error_types:
    parse_date_failed: "解析回傳資料失敗"
    date_not_in_db: "爬蟲取得資料不存在於資料庫"

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default

