---
:verbose: false
:concurrency: 3
:queues:
  - [default, 1]
  - [crawler_verdict, 2]
:limits:
  default: 1
  crawler_verdict: 2
staging:
  :concurrency: 2
  :queues:
  - [default, 1]
  - [crawler_verdict, 1]
  :limits:
    default: 1
    crawler_verdict: 1
production:
  :concurrency: 3
