---
:verbose: false
:concurrency: 3
:queues:
  - [default, 1]
  - [crawler_schedule, 1]
  - [crawler_referee, 2]
  - [import_referee, 1]
:limits:
  default: 1
  crawler_schedule: 1
  crawler_referee: 2
  import_referee: 2
staging:
  staging:
  :concurrency: 3
  :queues:
    - [default, 1]
    - [crawler_schedule, 1]
    - [crawler_referee, 2]
    - [import_referee, 1]
  :limits:
    default: 1
    crawler_schedule: 1
    crawler_referee: 2
    import_referee: 2

production:
  :concurrency: 3
  :queues:
    - default
    - import_referee
  :limits:
    import_referee: 2




